### ISSUE TITLE
fits2fits should work with astropy, but needs pyfits

### ISSUE THREAD

**Issue by cdeil** [telegraphic/fits2hdf#6]
It looks like `fits2hdf` uses `pyfits` in a few places internally, leading to this error if you only have `astropy.io.fits`:

```
$ /Users/deil/Library/Python/2.7/bin/fits2fits a.fits 
Traceback (most recent call last):
  File "/Users/deil/Library/Python/2.7/bin/fits2fits", line 9, in <module>
    load_entry_point('fits2hdf==1.0', 'console_scripts', 'fits2fits')()
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/fits2hdf-1.0-py2.7.egg/fits2hdf/file_conversion.py", line 18, in <module>
    from fits2hdf.io.hdfio import *
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/fits2hdf-1.0-py2.7.egg/fits2hdf/io/hdfio.py", line 9, in <module>
    import pyfits as pf
ImportError: No module named pyfits
```

It should work with astropy.io.fits (and if you have users that need the old pyfits, that also).

**Comment by telegraphic** [comment]
Ugh, that was a poor oversight. Away from office at the moment but this one was straightforward so I've changed all occurences to use `astropy.io.fits` instead.
